# Generated by Django 5.2.8 on 2025-12-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EloRating',
        ),
    ]
